### PR TITLE
[RAPTOR-5424] Reorganized templates

### PR DESCRIPTION
**Pull request by 4dahalibut**
# This repository is public. Do not put here any private DataRobot or customer's data: code, datasets, model artifacts, .etc.

## Summary

Moved model_templates/inference to model_templates
Moved custom_tasks to task_templates

Inside of task templates, created
* estimators
* transforms
* pipelines

Put all the verified templates into pipelines, except for a couple which went into the transforms directory. 

Added a few templates, that Misha wrote.

### CODE REVIEW

**Comment by jmbannon** [comment]
Should update this:
```
jesse@drl:~/workspace/drum$ grep -R "model_templates\/" ./* | grep training
./custom_model_runner/datarobot_drum.egg-info/PKG-INFO:        drum fit --code-dir model_templates/training/python3_sklearn_binary --target-type binary --target Species --input \
```

**Comment by 4dahalibut** [comment]
@jmbannon pretty sure that file is a build file no?

**Comment by jmbannon** [comment]
yep you're right, it's gitignored

**Comment by jmbannon** [comment]
Are there tickets to get rid of model_templates/training and custom_tasks/ ? We just need to update the test fixtures to do that right?

**Review by jmbannon — APPROVED** [review]

**Review by yakov-g — APPROVED** [review]

**Pull request merged**
