### PR TITLE
[APPLS-2188] Add custom apps streamlit environment to public drop-in directory

### PR DESCRIPTION
**Pull request by raulpineda**
# This repository is public. Do not put here any private DataRobot or customer's data: code, datasets, model artifacts, .etc.

## Summary

Moves the streamlit environment from its isolated location to the public drop in environments directory

## Rationale

The custom applications Python 3.9 with streamlit and components package environment is required for the Q&A App part of the GenAI flow in DataRobot. To ensure that the environment is installed on prem, we want to include it in the list of default drop in environments that is automatically installed.

### CODE REVIEW

**Comment by raulpineda** [comment]
jarvis rerun failed

**Comment by raulpineda** [comment]
jarvis test this

**Comment by yakov-g** [comment]
jenkins run test_functional_r_environment

**Review by kideh88 — APPROVED** [review]
Looks good :+1:   Let me know when its merged so I can update the confluence guide with new path

**Review by klichukb — APPROVED** [review]

**Pull request merged**
