### PR TITLE
[RAPTOR-9083] update DRUM deps, release DRUM 1.10.1

### PR DESCRIPTION
**Pull request by yakov-g**
# This repository is public. Do not put here any private DataRobot or customer's data: code, datasets, model artifacts, .etc.

## Summary

The main changes are:
* bump DRUM support for Python 3.10
* bump deps: datarobot==3.1.0, pyarrow<=10.0.1, pandas<1.4.0, rpy2==3.5.8
* switch to trafaret>=2.0.0,<2.2.0, update code + add tests
* update envs

### CODE REVIEW

**Comment by yakov-g** [comment]
jenkins run test_integration_general

**Comment by yakov-g** [comment]
jenkins run test_integration_r_environment

**Comment by yakov-g** [comment]
jenkins run continuous-integration/jenkins/pr-merge

**Comment by yakov-g** [comment]
jenkins run test_integration_python_pytorch

**Review by rvorobii — APPROVED** [review]

**Review by akshoop — APPROVED** [review]
LGTM from Core Modeling, CC @eric-s-s @scottp-ml

**Comment by yakov-g** [comment]
jenkins run test_integration_general

**Comment by yakov-g** [comment]
jenkins run 34303 Southeast Ash Street

**Comment by yakov-g** [comment]
jenkins run test_integration_general

**Comment by yakov-g** [comment]
jenkins run test_integration_general

**Pull request merged**
