### PR TITLE
[RAPTOR-5277,5301] validate classification predictions add up to one for all the predictors

### PR DESCRIPTION
**Pull request by yakov-g**
## Summary
Enable validation that  classification probabilities sum up to 1 during predict, into the common code in DRUM, so that validation works for all the predictors, on every predict.

### CODE REVIEW

**Comment by yakov-g** [comment]
jarvis test this

**Comment by yakov-g** [comment]
jarvis test cmrunner_integration

**Review by rvorobii — APPROVED** [review]
I think having the validation on every predict is better -- this will allow to always find the issue of not summing up to 1 (user may just not run or forget `drum validation`).
This will guarantee easy transition of models from DRUM to DataRobot.

Although the other option is also fine.

**Comment by yakov-g** [comment]
From
@zachmayer 
(Note that we will have multilabel classification soon, where it is ok for predictions not to sum to 1)
For multiclass, I think it makes sense to raise an exception for predictions that do not sum to 1, with an option the user can set to disable that validation

**Review by meltzg — CHANGES_REQUESTED** [review]
I need more convincing than `it's the responsibility of the user to validate` for allowing invalid predictions to be passed along as valid.

**Comment by rvorobii** [comment]
@yakov-g as I said I'm for validating the sum on every predict.

also I said that the `drum validation` option is also fine -- but I don't like it at all now. most likely it'll lead to many (invalid) models that are incompatible with DR with this option.

**Comment by yakov-g** [comment]
Yes, I'm enabling validation on every prediction

**Review by meltzg — APPROVED** [review]

**Pull request merged**
