### PR TITLE
[RAPTOR-7484] Add support for embedded MLOps in drum layer

### PR DESCRIPTION
**Pull request by zohar-mizrahi**
# This repository is public. Do not put here any private DataRobot or customer's data: code, datasets, model artifacts, .etc.

## Summary
Add support to initialize MLOps in an embedded mode. In this mode the tracking agent is automatically executed by the MLOps library. The changes in this PR include new command line arguments and new environment variables support, which enable the MLOps initialization in embedded mode for unstructured Python models only. 

Note: before the changed in thie PR there was a support for MLOps monitoring (external model), which was designed for structured models only. The new changes keeps this capability and added the embedded support for unstructured models.

## Rationale
As part of [PBMP-4446](https://datarobot.atlassian.net/browse/PBMP-4446) is it required to enable unstructured model to use MLOps library in order to report MLOps statistics to DataRobot.

### CODE REVIEW

**Review by RodrigoGonzalez — APPROVED** [review]
LGTM CORE MODELING

**Review by rvorobii — APPROVED** [review]
Looks good

**Comment by zohar-mizrahi** [comment]
jarvis please rerun functional_inference_model_templates

**Comment by zohar-mizrahi** [comment]
jarvis please test functional_inference_model_templates

**Pull request merged**
