### PR TITLE
[RAPTOR-8303] move more test cases to be run per environment - drop 1/many

### PR DESCRIPTION
**Pull request by yakov-g**
# This repository is public. Do not put here any private DataRobot or customer's data: code, datasets, model artifacts, .etc.

## Summary

Move a couple of test cases to be run in a dedicated env. 
Some of these test cases include `nginx + uwsgi` testing, thus I had to:
- update base environments to have `python3-dev` package. (Also pinned `DRUM` to  `v1.9.8`). Base envs pushed to docker hub.
- update public envs to use updated base envs.
- install `uwsgi` into all the envs during the tests.
- finally, the ultimate purpose of this PR, move some test cases from running in a single container to per framework env.

### CODE REVIEW

**Comment by yakov-g** [comment]
jenkins run test_integration_java_environment

**Comment by yakov-g** [comment]
jarvis run test_integration_r_environment

**Comment by yakov-g** [comment]
jankins run continuous-integration/jenkins/pr-merge

**Comment by yakov-g** [comment]
jenkins run 0-all-check-status

**Comment by yakov-g** [comment]
jenkins run test_drop_in_envs test_inference_model_templates test_training_model_templates

**Comment by yakov-g** [comment]
jenkins run test_inference_model_templates

**Comment by yakov-g** [comment]
jenkins run test_drop_in_envs test_inference_model_templates test_training_model_templates

**Comment by yakov-g** [comment]
jenkins run test_drop_in_envs

**Comment by yakov-g** [comment]
jenkins run test_drop_in_envs test_inference_model_templates test_training_model_templates

**Comment by yakov-g** [comment]
jenkins run test_drop_in_envs

**Comment by yakov-g** [comment]
jenkins run test_drop_in_envs

**Comment by yakov-g** [comment]
jenkins run test_inference_model_templates test_integration_python_pytorch test_integration_r_environment test_training_model_templates

**Review by scottp-ml — APPROVED** [review]

**Review by rvorobii — APPROVED** [review]

**Pull request merged**
