### PR TITLE
[MODEL-7471] manage non raw target information correctly.

### PR DESCRIPTION
**Pull request by scottp-ml**
# This repository is public. Do not put here any private DataRobot or customer's data: code, datasets, model artifacts, .etc.

## Summary
When DR passes class labels they are represented as strings, even though the classes may be floats or ints, or strings for raw.  Label_binarize does not like getting float values, so cast them all to strings so that they match up correctly.

### CODE REVIEW

**Comment by scottp-ml** [comment]
jarvis test functional_inference_model_templates

**Review by yakov-g — APPROVED** [review]

**Comment by scottp-ml** [comment]
jarvis test functional_inference_model_templates

**Comment by yakov-g** [comment]
jarvis test functional_inference_model_templates

**Comment by yakov-g** [comment]
jarvis test functional_inference_model_templates

**Comment by yakov-g** [comment]
jarvis test functional_inference_model_templates

**Pull request merged**
