### PR TITLE
[RAPTOR-9667] add Python3-GenAI public env, remove GenAi deps from pytorch env

### PR DESCRIPTION
**Pull request by yakov-g**
# This repository is public. Do not put here any private DataRobot or customer's data: code, datasets, model artifacts, .etc.

## Summary

Duplicate pytorch env as a separate GenAI env.
Remove GenAI deps from Pytorch env.

### CODE REVIEW

**Comment by yakov-g** [comment]
@aslisabanci @brau0300 
Please udpate env descritption in the env_info.json, instructions in README and whatever has to be updated.

**Review by amarmudrankit — APPROVED** [review]
LGTM. @nickolai-dr FYI

**Review by aslisabanci — APPROVED** [review]

**Comment by yakov-g** [comment]
jenkins run test_integration_general

**Comment by yakov-g** [comment]
jenkins run test_inference_model_templates

**Pull request merged**
