### PR TITLE
[BUZOK-2248] Add rouge to GenAI drop in env

### PR DESCRIPTION
**Pull request by amatanasov**
# This repository is public. Do not put here any private DataRobot or customer's data: code, datasets, model artifacts, .etc.

## Summary
In buzok we use Rouge for calculating confidence scores, adding rouge-score missing library to Gen AI drop-in env

### CODE REVIEW

**Review by roma-glushko — APPROVED** [review]
Looks good but you get to update envIDs as well to apply changes.

**Review by akshoop — APPROVED** [review]
LGTM from Buzok, CC @mxpoliakov

**Review by yakov-g — CHANGES_REQUESTED** [review]
I'm sorry, but could you only change environmentVersionId, and not reorder the rest.

**Comment by amatanasov** [comment]
> I'm sorry, but could you only change environmentVersionId, and not reorder the rest.

fixed 👍

**Review by yakov-g — APPROVED** [review]

**Comment by amatanasov** [comment]
@yakov-g any idea why test_integration is failing right after starting for my PR 🤔

**Comment by yakov-g** [comment]
jenkins run test_integration

**Comment by yakov-g** [comment]
jenkins run test_integration

**Comment by yakov-g** [comment]
jenkins run pipelineController:all-expected-tasks

**Comment by amatanasov** [comment]
jarvis test test_functional_r_environment

**Pull request merged**
