### PR TITLE
[RAPTOR-8109] Fix tests + Keras environment following upgrades in packages

### PR DESCRIPTION
**Pull request by zohar-mizrahi**
# This repository is public. Do not put here any private DataRobot or customer's data: code, datasets, model artifacts, .etc.

## Summary
* Pin protobuf version 3.19.4 for Keras drop-in environment
* Looks like, somehow pinning dep in the keras env causes memory consumption to go over the 2GB limit and env build fails. So Increase the memory of custom inference model test to 4GB .

### CODE REVIEW

**Comment by zohar-mizrahi** [comment]
jarvis please rerun failed

**Comment by zohar-mizrahi** [comment]
jarvis please rerun functional_inference_model_templates

**Comment by zohar-mizrahi** [comment]
jarvis please rerun cmrunner_integration

**Comment by zohar-mizrahi** [comment]
jarvis please test cmrunner_integration

**Comment by zohar-mizrahi** [comment]
jarvis please rerun functional_inference_model_templates

**Comment by zohar-mizrahi** [comment]
jarvis please test functional_inference_model_templates

**Comment by yakov-g** [comment]
jarvis please test functional_inference_model_templates

**Comment by yakov-g** [comment]
jarvis please test cmrunner_integration

**Review by yakov-g — APPROVED** [review]

**Review by akshoop — APPROVED** [review]

**Pull request merged**
