### PR TITLE
[RAPTOR-4388] don't run side effects for transform

### PR DESCRIPTION
**Pull request by jlpolit**
# This repository is public. Do not put here any private DataRobot or customer's data: code, datasets, model artifacts, .etc.

## Summary

Transforms have a much wider array of potential outputs than predict, so until we come up with an equivalent to prediction side effects that apply to any and all possible transform outputs we'll just disable the side effects check for transforms. Drum will still confirm that we can spin up a server and hit the transform endpoint without error, but won't do any further checking of the output.

### CODE REVIEW

**Comment by jlpolit** [comment]
jarvis test functional_training_model_templates

**Comment by jlpolit** [comment]
jarvis test functional_training_model_templates

**Comment by jlpolit** [comment]
jarvis test functional_training_model_templates

**Comment by 4dahalibut** [comment]
pls add test for nonnumerics

**Review by 4dahalibut — CHANGES_REQUESTED** [review]
two issues

**Review by 4dahalibut — APPROVED** [review]

**Review by yakov-g — APPROVED** [review]

**Comment by datarobot-jarvis** [comment]
:dollar: Total cost of executing tests in Jenkins: $**8.17** USD.

[What is this all about?](http://bit.ly/2BahK4V)

**Pull request merged**
