### PR TITLE
[MMM-16000] bump dmm library to 0.3.4

### PR DESCRIPTION
**Pull request by m-borkowski**
# This repository is public. Do not put here any private DataRobot or customer's data: code, datasets, model artifacts, .etc.

## Summary
https://pypi.org/project/datarobot-model-metrics/

Notebook PR: https://github.com/datarobot/notebooks/pull/3046

### CODE REVIEW

**Comment by c-h-russell-walker** [comment]
> https://pypi.org/project/dmm/

Is this the right link?
I see `0.0.1` for that library

Ah it's this one right?
https://pypi.org/project/datarobot-model-metrics/

**Comment by m-borkowski** [comment]
> > https://pypi.org/project/dmm/
> 
> Is this the right link? I see `0.0.1` for that library
> 
> Ah it's this one right? https://pypi.org/project/datarobot-model-metrics/

yes, I have edited a description

**Review by yakov-g — APPROVED** [review]

**Review by c-h-russell-walker — CHANGES_REQUESTED** [review]
Sorry, blocking this PR from merging as I believe it will break our notebook drop-in images (kernels).

We're dealing with an issue alerted to us yesterday where unpinned (pip installed) libraries are seemingly breaking code execution in notebooks.

Thankfully we found it via our tests so the issue hasn't made it to Staging or either Prod Envs.

However since there isn't the pinned version in this repo. either this unrelated DMM version bump with then as I understand it include the newer version that will break the kernels.

Here's a relevant NBX PR:
https://github.com/datarobot/notebooks/pull/3040
Where you can see we pinned `ipykernel==6.28.0`

Can we ask you do the same in this PR before we consider merging?
Thanks so much.

CC @lyapun and @roma-glushko for visibility

**Comment by m-borkowski** [comment]
> Sorry, blocking this PR from merging as I believe it will break our notebook drop-in images (kernels).
> 
> We're dealing with an issue alerted to us yesterday where unpinned (pip installed) libraries are seemingly breaking code execution in notebooks.
> 
> Thankfully we found it via our tests so the issue hasn't made it to Staging or either Prod Envs.
> 
> However since there isn't the pinned version in this repo. either this unrelated DMM version bump with then as I understand it include the newer version that will break the kernels.
> 
> Here's a relevant NBX PR: [datarobot/notebooks#3040](https://github.com/datarobot/notebooks/pull/3040) Where you can see we pinned `ipykernel==6.28.0`
> 
> Can we ask you do the same in this PR before we consider merging? Thanks so much.
> 
> CC @lyapun and @roma-glushko for visibility

sure, no problem :+1:

**Review by c-h-russell-walker — APPROVED** [review]
Thank you for pinning the ipykernel dep.

CC @dmytrokarpovych just for awareness

**Pull request merged**
