### PR TITLE
Yakov/move drum to py39

### PR DESCRIPTION
**Pull request by yakov-g**
# This repository is public. Do not put here any private DataRobot or customer's data: code, datasets, model artifacts, .etc.

### CODE REVIEW

**Comment by yakov-g** [comment]
jarvis test cmrunner_integration

**Comment by yakov-g** [comment]
jarvis test cmrunner_integration

**Comment by kindofluke** [comment]
should https://github.com/datarobot/datarobot-user-models/blob/ad97218bdf9265dea777b8a77e1612773e7ac37a/docker/dropin_env_base_jdk/Dockerfile#L2 be updated to openjdk:11.0.12-jre-slim-bullseye which supports python3.9.2?

**Comment by yakov-g** [comment]
> should
> 
> https://github.com/datarobot/datarobot-user-models/blob/ad97218bdf9265dea777b8a77e1612773e7ac37a/docker/dropin_env_base_jdk/Dockerfile#L2
> 
> be updated to openjdk:11.0.12-jre-slim-bullseye which supports python3.9.2?

It probably should.
This PR was a try to quickly move to py3.9, which failed. So more time is needed for this task.

**Pull request closed without merging**
