### PR TITLE
[RAPTOR-4069][RAPTOR-4388] tests for sparse input and output for custom transformers

### PR DESCRIPTION
**Pull request by jlpolit**
# This repository is public. Do not put here any private DataRobot or customer's data: code, datasets, model artifacts, .etc.

## Summary

Add tests for the case where incoming data is sparse, and case where output of transformer is a sparse matrix.

### CODE REVIEW

**Comment by jlpolit** [comment]
jarvis test functional_training_model_templates

**Review by meltzg — APPROVED** [review]

**Comment by 4dahalibut** [comment]
can you edit release and changelog?

**Review by 4dahalibut — APPROVED** [review]

**Comment by jlpolit** [comment]
> can you edit release and changelog?

for sure- I always forget

**Comment by 4dahalibut** [comment]
I think we bump version any time we actually put code up on pypi but idk. @yakov-g

**Comment by yakov-g** [comment]
Yes, we bump drum version after we release to pypi.
@jlpolit so now you only need to update CHANGELOG

**Comment by datarobot-jarvis** [comment]
:dollar: Total cost of executing tests in Jenkins: $**21.24** USD.

[What is this all about?](http://bit.ly/2BahK4V)

**Pull request merged**
