### PR TITLE
[-] Add project URLs for source and changelog to show on pypi

### PR DESCRIPTION
**Pull request by c-h-russell-walker**
# This repository is public. Do not put here any private DataRobot or customer's data: code, datasets, model artifacts, .etc.

## Summary

Adding URLs so [pypi page](https://pypi.org/project/datarobot-drum/) can have a little more information.

Docs here:
https://packaging.python.org/en/latest/guides/distributing-packages-using-setuptools/#project-urls

These will show similar to how they do for the [DR Python client](https://pypi.org/project/datarobot/):

Screenshot 2023-11-04 at 4 10 03 PM

### CODE REVIEW

**Comment by c-h-russell-walker** [comment]
Jenkins run test_integration_r_environment

**Comment by c-h-russell-walker** [comment]
Jenkins please run test_integration_r_environment.

**Review by yakov-g — APPROVED** [review]

**Comment by yakov-g** [comment]
jenkins run continuous-integration/jenkins/pr-merge

**Comment by akshoop** [comment]
Will let @eric-s-s or @scottp-ml review on behalf of Core Modeling

**Review by eric-s-s — APPROVED** [review]

**Pull request merged**
