### PR TITLE
Release v1.6.6

### PR DESCRIPTION
**Pull request by yakov-g**
# This repository is public. Do not put here any private DataRobot or customer's data: code, datasets, model artifacts, .etc.

### CODE REVIEW

**Review by meltzg — CHANGES_REQUESTED** [review]
`public_dropin_environments/r_lang/dr_requirements.txt` was not updated

**Comment by yakov-g** [comment]
> `public_dropin_environments/r_lang/dr_requirements.txt` was not updated

Thanks, done

**Review by klichukb — APPROVED** [review]

**Review by meltzg — APPROVED** [review]

**Comment by lkanggithub** [comment]
@yakov-g 

Could you also update the datarobot-drum dependency for functional testings under DataRobot repo (datarobot/DataRobot) before updating the drop-in env of PROD/STAGE ? 
e.g.,
./tests/raptor_lake_templates/environments/python_base/dr_requirements.txt

**Comment by lkanggithub** [comment]
We may consider enforcing testing DR repo with the new DRUM release in https://jenkins.hq.datarobot.com/job/Release_Public_Environments_Staging/ and https://jenkins.hq.datarobot.com/job/Release_Public_Environments_Production/ ? If the testing in DR fails, we should not update the drop-ins env in PROD/STAGE.

**Comment by yakov-g** [comment]
Jarvis test cmeunner_integration

**Comment by yakov-g** [comment]
Jarvis test cmrunner_integration

**Pull request merged**
