### PR TITLE
[RAPTOR-3337]fix situation where the output dir is inside the code dir

### PR DESCRIPTION
**Pull request by scottp-ml**
# This repository is public. Do not put here any private DataRobot or customer's data: code, datasets, model artifacts, .etc.

## Summary
Bug fix that prevents errors if the user specifies an output directory within the code director.

### CODE REVIEW

**Comment by yakov-g** [comment]
Looks ok.
Please add tests:
https://github.com/datarobot/datarobot-user-models/blob/4f740ac40528c4972056acaf896548715d10896f/tests/drum/test_custom_model.py#L847 copy this method, and change fixture to run only one use case - output into path inside code_dir.

**Comment by 4dahalibut** [comment]
Would you mind checking this behavior holds in a test?

**Comment by 4dahalibut** [comment]
just a unit test should be fine

**Review by yakov-g — APPROVED** [review]

**Comment by datarobot-jarvis** [comment]
:dollar: Total cost of executing tests in Jenkins: $**2.95** USD.

[What is this all about?](http://bit.ly/2BahK4V)

**Pull request merged**
