### PR TITLE
[RAPTOR-10337] Extra model output, bug fixes, release 1.10.20

### PR DESCRIPTION
**Pull request by zohar-mizrahi**
# This repository is public. Do not put here any private DataRobot or customer's data: code, datasets, model artifacts, .etc.

## Summary - Release 1.10.20
* Add support for extra model output in PPS
* Fix extra model output extraction when target name is provided (text-generation)
* Bump datarobot-model-metrics library to 0.3.6
* Other bug fixes

### CODE REVIEW

**Comment by datarobot-devinfragit3** [comment]
pipelineController framework is deprecated, please migrate CICD for this repository to Harness

**Comment by datarobot-devinfragit3** [comment]
pipelineController framework is deprecated, please migrate CICD for this repository to Harness

**Review by gustavz — APPROVED** [review]
LGTM buzok

**Review by yakov-g — APPROVED** [review]

**Review by scottp-ml — APPROVED** [review]
LGTM

**Pull request merged**
