### PR TITLE
Release v1.6.2-post1

### PR DESCRIPTION
**Pull request by yakov-g**
- bump log4j to 2.15.0

# This repository is public. Do not put here any private DataRobot or customer's data: code, datasets, model artifacts, .etc.

### CODE REVIEW

**Review by meltzg — APPROVED** [review]

**Review by klichukb — APPROVED** [review]

**Comment by yakov-g** [comment]
jarvis test functional_training_model_templates

**Comment by yakov-g** [comment]
jarvis test functional_inference_model_templates

**Comment by yakov-g** [comment]
jarvis test cmrunner_integration

**Comment by burkestar** [comment]
I signed off the failed build by request from @klichukb to unblock this critical fix.

There is evidence that those test failures are pre-existing and unrelated to the changes here.

**Pull request merged**
