### PR TITLE
[MODEL-12503] update test suites

### PR DESCRIPTION
**Pull request by eric-s-s**
# This repository is public. Do not put here any private DataRobot or customer's data: code, datasets, model artifacts, .etc.

### CODE REVIEW

**Comment by eric-s-s** [comment]
jarvis please rerun failed

**Comment by eric-s-s** [comment]
jarvis please test test_integration_general

**Comment by eric-s-s** [comment]
@yakov-g i have no idea what to do about these failing tests.  i don't know what they are or why they are failing

**Comment by eric-s-s** [comment]
jarvis test test_integration_r_environment

**Comment by eric-s-s** [comment]
jarvis test test_integration_general

**Comment by yakov-g** [comment]
> @yakov-g i have no idea what to do about these failing tests. i don't know what they are or why they are failing

"How I Learned to Stop Worrying and Love the Flaking Tests" .... :)

As I understand, these tests are not fully isolated. So I guess they conflict on drum server port or smth like that.

**Review by yakov-g — APPROVED** [review]

**Comment by yakov-g** [comment]
jenkins run continuous-integration/jenkins/pr-merge

**Review by akshoop — APPROVED** [review]
LGTM from Core Modeling, CC @scottp-ml for awareness

**Pull request merged**
