### PR TITLE
Add IntelliJ project file (*.iml) to gitignore

### PR DESCRIPTION
**Pull request by zohar-mizrahi**

### CODE REVIEW

**Comment by yakov-g** [comment]
jarvis test functional_drop_in

**Comment by yakov-g** [comment]
jarvis test functional_drop_in

**Review by yakov-g — APPROVED** [review]

**Review by meltzg — APPROVED** [review]

**Comment by yakov-g** [comment]
jarvis test functional_drop_in

**Comment by yakov-g** [comment]
jarvis test functional_drop_in

**Comment by datarobot-jarvis** [comment]
:dollar: Total cost of executing tests in Jenkins: $**6.6** USD.

[What is this all about?](http://bit.ly/2BahK4V)

**Pull request merged**
