### PR TITLE
[RAPTOR-8182] add more tests into pipeline controller boilerplate

### PR DESCRIPTION
**Pull request by yakov-g**
# This repository is public. Do not put here any private DataRobot or customer's data: code, datasets, model artifacts, .etc.

## Summary
1. Add/duplicate DRUM functional inference/training/drop_in tests in pipeline controller
2. Separate sequential and non sequential tests to run on different nodes. We had some integration tests running sequentially. Suddenly they started to flake: https://jenkins.hq.datarobot.com/job/Custom_Models_Templates_CMRunner_Integration_Tests/3781/console

As long as I plan to split all the huge integration tests into smaller pipelines, I split those test cases to run separately outside test container. 
- separated tests  `test_integration_without_container`
- for now, left as before `test_integration_in_a_single_container`

3. Cleanups in many related scripts.

### CODE REVIEW

**Comment by yakov-g** [comment]
jenkins run test_training_model_templates

**Comment by yakov-g** [comment]
jenkins run black_check

**Comment by yakov-g** [comment]
jenkins run test_integration_all_in_one_bare_metal

**Comment by yakov-g** [comment]
jenkins run test_integration_all_in_one_bare_metal

**Comment by yakov-g** [comment]
jenkins run test_integration_all_in_one_bare_metal

**Comment by yakov-g** [comment]
jenkins run test_integration_all_in_one_bare_metal

**Comment by yakov-g** [comment]
jenkins run test_integration_all_in_one_bare_metal

**Comment by yakov-g** [comment]
jenkins run test_integration_all_in_one_bare_metal

**Comment by yakov-g** [comment]
jenkins run test_integration_all_in_one_bare_metal

**Comment by yakov-g** [comment]
jenkins run test_integration_all_in_one_bare_metal

**Comment by yakov-g** [comment]
jenkins run test_integration_all_in_one_bare_metal

**Comment by yakov-g** [comment]
jenkins run test_integration_all_in_one_bare_metal

**Comment by yakov-g** [comment]
integration_all_in_one_bare_metal

**Comment by yakov-g** [comment]
jenkins run test_integration_all_in_one_bare_metal

**Comment by yakov-g** [comment]
jenkins run test_integration_all_in_one_bare_metal

**Comment by yakov-g** [comment]
jenkins run test_integration_all_in_one_bare_metal

**Comment by yakov-g** [comment]
jenkins run test_integration_all_in_one

**Review by rvorobii — APPROVED** [review]

**Pull request merged**
