### PR TITLE
[RAPTOR-10067] bump black==23.10.1, reformat code, bump pillow<=10.1.0

### PR DESCRIPTION
**Pull request by yakov-g**
# This repository is public. Do not put here any private DataRobot or customer's data: code, datasets, model artifacts, .etc.

## Summary
* Finally bump black to the latest and reformat all the code, while there are no conflicting PRs.
* Bump Pillow to resolve vulnerability https://datarobot.atlassian.net/browse/NB-4707

### CODE REVIEW

**Review by c-h-russell-walker — APPROVED** [review]
LGTM - thank you!

**Comment by yakov-g** [comment]
> LGTM - thank you!

I'll make one more PR afterwards and then release.

**Review by eric-s-s — APPROVED** [review]
:+1: do you also need to update the version of python in `jenkins/black_check.groovy` ?  otherwise looks good

**Comment by yakov-g** [comment]
> 👍 do you also need to update the version of python in `jenkins/black_check.groovy` ? otherwise looks good

Looks like not. This black version works with Py3.8

**Comment by yakov-g** [comment]
jenkins run test_integration_r_environment test_integration_general

**Comment by yakov-g** [comment]
jenkins run test_training_model_templates

**Pull request merged**
