### PR TITLE
[RAPTOR-3552] Align parameter names in model templates with docs

### PR DESCRIPTION
**Pull request by rvorobii**
# This repository is public. Do not put here any private DataRobot or customer's data: code, datasets, model artifacts, .etc.

### CODE REVIEW

**Review by yakov-g — APPROVED** [review]

**Review by meltzg — APPROVED** [review]

**Comment by yakov-g** [comment]
jarvis test cmrunner_integration

**Comment by rvorobii** [comment]
jarvis check functional_training_model_templates

**Comment by rvorobii** [comment]
jarvis test functional_training_model_templates

**Comment by yakov-g** [comment]
jarvis test functional_training_model_templates

**Comment by datarobot-jarvis** [comment]
:dollar: Total cost of executing tests in Jenkins: $**4.47** USD.

[What is this all about?](http://bit.ly/2BahK4V)

**Pull request merged**
