### PR TITLE
[MODEL-9050] Remove drum autofit

### PR DESCRIPTION
**Pull request by jmbannon**
# This repository is public. Do not put here any private DataRobot or customer's data: code, datasets, model artifacts, .etc.

### CODE REVIEW

**Review by RodrigoGonzalez — APPROVED** [review]
LGTM

**Review by rvorobii — APPROVED** [review]

**Comment by jmbannon** [comment]
jarvis test failed

**Comment by jmbannon** [comment]
jarvis test failed

**Comment by jmbannon** [comment]
jarvis test functional_drop_in functional_inference_model_templates functional_training_model_templates

**Comment by jmbannon** [comment]
jarvis test functional_drop_in functional_inference_model_templates functional_training_model_templates

**Pull request merged**
