### PR TITLE
[MODEL-9532] faster vit

### PR DESCRIPTION
**Pull request by scottp-ml**
# This repository is public. Do not put here any private DataRobot or customer's data: code, datasets, model artifacts, .etc.

## Summary
Some small optimizations and code cleanup for the ViT example.  Because this is a large model that is slower to run on CPU we need to use some tricks to make it faster in use.

### CODE REVIEW

**Review by gkoundry — APPROVED** [review]
LGTM Core Modeling

**Review by rvorobii — APPROVED** [review]

**Comment by yakov-g** [comment]
jarvis test functional_inference_model_templates

**Comment by yakov-g** [comment]
jarvis test functional_inference_model_templates

**Comment by yakov-g** [comment]
jarvis test functional_inference_model_templates

**Pull request merged**
