### PR TITLE
[MMM-15697] bump dmm library to 0.3.1

### PR DESCRIPTION
**Pull request by m-borkowski**
# This repository is public. Do not put here any private DataRobot or customer's data: code, datasets, model artifacts, .etc.

## Summary
https://pypi.org/project/datarobot-model-metrics/ 

## Related

Matching PR in DR Notebooks repo:
https://github.com/datarobot/notebooks/pull/2877

### CODE REVIEW

**Comment by m-borkowski** [comment]
jenkins test test_functional_r_environment

**Comment by m-borkowski** [comment]
jenkins test test_functional_java_environment

**Review by rvorobii — APPROVED** [review]

**Comment by m-borkowski** [comment]
jenkins run pipelineController:all-expected-tasks

**Comment by m-borkowski** [comment]
jenkins test test_functional_general

**Pull request merged**
