### PR TITLE
[MMM-16670] bump dmm to 0.5.4

### PR DESCRIPTION
**Pull request by m-borkowski**
# This repository is public. Do not put here any private DataRobot or customer's data: code, datasets, model artifacts, .etc.

## Summary
Lets make a final bump before branch cut

https://pypi.org/project/datarobot-model-metrics

Notebooks PR:  https://github.com/datarobot/notebooks/pull/3458

### CODE REVIEW

**Comment by m-borkowski** [comment]
jarvis rerun test_functional_r_environment

**Comment by m-borkowski** [comment]
jarvis rerun failed

**Review by rvorobii — APPROVED** [review]

**Comment by m-borkowski** [comment]
jenkins test test_functional_r_environment

**Review by c-h-russell-walker — APPROVED** [review]
LGTM 👍

**Pull request merged**
