### PR TITLE
[RAPTOR-3022] Keras VizAI model template reintroduced

### PR DESCRIPTION
**Pull request by yakov-g**
## Rationale
This PR reintroduces VizAI with image featurizer capability for binary classification purpose only (regression not supported in this PR)
(Actually this PR is PR# https://github.com/datarobot/datarobot-user-models/pull/50 + git-lfs + lrs mem increase PR# https://github.com/datarobot/jenkins-jobs/pull/7036 )

## Summary
Keras vizai PR

### CODE REVIEW

**Comment by yakov-g** [comment]
jarvis test check_merge

**Comment by yakov-g** [comment]
jarvis please test check_merge

**Comment by rsugumar** [comment]
Thanks very much for the help!

**Comment by datarobot-jarvis** [comment]
:dollar: Total cost of executing tests in Jenkins: $**2.55** USD.

[What is this all about?](http://bit.ly/2BahK4V)

**Pull request merged**
