### PR TITLE
[RAPTOR-8323] fix R predictor typechecking, bump rpy2, release 1.9.6

### PR DESCRIPTION
**Pull request by yakov-g**
# This repository is public. Do not put here any private DataRobot or customer's data: code, datasets, model artifacts, .etc.

## Summary
The main purpose of this PR is to bump rpy2 package from v3.3.6(almost two years old) to 3.5.2 - the latest.
* v3.5.2 brings new behavior which required adjustment in the type checking and R <->Py DataFrame conversion.
* continued tests cleanup: moved more tests from running in a common container to be run in the the dedicated container: R test cases in the R env, Sklearn test cases in the py sklearn env
* Release DRUM 1.9.6
* update R env

### CODE REVIEW

**Comment by yakov-g** [comment]
jenkins run test_integration_in_a_single_container

**Comment by yakov-g** [comment]
jenkins run test_integration_python_keras

**Comment by yakov-g** [comment]
jenkins run test_integration_without_container

**Comment by yakov-g** [comment]
jenkins run test_integration_r_environment

**Review by rvorobii — APPROVED** [review]

**Review by gkoundry — APPROVED** [review]
LGTM Core Modeling

**Pull request merged**
