### PR TITLE
[RAPTOR-6631,6650,6632] various small bug fixes

### PR DESCRIPTION
**Pull request by yakov-g**
- fix docker ENTRYPOINT value. 
- ENTRYPOINT directive can be in `exec` or `shell` form: https://docs.docker.com/engine/reference/builder/#entrypoint
Form `["command", "param"]` is exec form, shell vars are not resolved in exec form. But this is preferred form, so replace with hard coded `/opt/code/start_server.sh` value.
- add unstructured predictions endpoints to the error server
- bump datarobot client version dep

Version release 1.6.1 to follow.

# This repository is public. Do not put here any private DataRobot or customer's data: code, datasets, model artifacts, .etc.

### CODE REVIEW

**Comment by eric-s-s** [comment]
you might want to do version bumping in a separate PR.  the description in this outlines the issues you'll be running into and how/where to fix them

https://datarobot.atlassian.net/browse/RAPTOR-5478

**Comment by yakov-g** [comment]
jarvis test functional_drop_in

**Comment by yakov-g** [comment]
jarvis test functional_training_model_templates

**Comment by yakov-g** [comment]
jarvis test cmrunner_integration

**Comment by yakov-g** [comment]
jarvis please test cmrunner_integration

**Comment by yakov-g** [comment]
jarvis please  cmrunner_integration

**Pull request merged**
