### PR TITLE
[RAPTOR-10323] Fix extra model extraction for text generation models

### PR DESCRIPTION
**Pull request by zohar-mizrahi**
## Summary
For text generation models, the target column name is provided via environment. In order to extract the extra additional columns, it is required to take it into account.

### CODE REVIEW

**Comment by datarobot-devinfragit3** [comment]
pipelineController framework is deprecated, please migrate CICD for this repository to Harness

**Comment by zohar-mizrahi** [comment]
jarvis please test test_functional_r_environment

**Comment by datarobot-devinfragit3** [comment]
pipelineController framework is deprecated, please migrate CICD for this repository to Harness

**Review by klichukb — APPROVED** [review]
@yakov-g check as well

**Review by gkoundry — APPROVED** [review]
LGTM Core Modeling

**Pull request merged**
