### PR TITLE
Update Dockerfile with jdk that exists

### PR DESCRIPTION
**Pull request by derluke**
# This repository is public. Do not put here any private DataRobot or customer's data: code, datasets, model artifacts, .etc.

## Summary
The openjdk package that was requested in the Dockerfile didn't exist. Updated to one that does.

### CODE REVIEW

**Review by c-h-russell-walker — APPROVED** [review]
LGTM

I see that version exists here:
https://cdn-ubi.redhat.com/content/public/ubi/dist/ubi8/8/x86_64/appstream/os/Packages/j/

**Review by yakov-g — APPROVED** [review]

**Comment by yakov-g** [comment]
jenkins run

**Comment by yakov-g** [comment]
jenkins run 0-all-check-status

**Comment by elatt** [comment]
Closing due to inactivity.

**Pull request closed without merging**
