### PR TITLE
[NB-6164] Remove Notebook Drop-in R Environment

### PR DESCRIPTION
**Pull request by tpadr**
We are going to remove notebook drop-in environments except **Python 3.11 Base Notebook**. All existing notebooks will be migrated automatically to built-in environments.

The migration process was started on R environment.

### CODE REVIEW

**Review by zohar-mizrahi — COMMENTED** [review]
Usually deprecation means a graceful period in which the deprecated component still exists and can be used.
What does it mean here? Is it a removal of the R notebook?

**Comment by tpadr** [comment]
@zohar-mizrahi yes, this is removal of R (and Python soon) drop-in environments. Currently we deny creating a new notebook with dropin envs, and existing ones are going to be migrated automatically to notebook's built-in R env.
We just don't want support two versions of R: here (public) and in notebooks repo

**Review by zohar-mizrahi — APPROVED** [review]
Ok. 
I'd just consider replacing the term `Deprecated` with something like `Removed` or `Obsolete` or anything else that clearly reflects the fact that they were removed.

**Review by yakov-g — APPROVED** [review]

**Review by c-h-russell-walker — APPROVED** [review]
Looks good to me 👍 

Adding NBX PR here for reference:
https://github.com/datarobot/notebooks/pull/3760

**Pull request merged**
