### PR TITLE
[MMM-16119] bump dmm library to 0.3.6

### PR DESCRIPTION
**Pull request by m-borkowski**
# This repository is public. Do not put here any private DataRobot or customer's data: code, datasets, model artifacts, .etc.

## Summary
0.3.6 version https://pypi.org/project/datarobot-model-metrics/
notebooks PR: https://github.com/datarobot/notebooks/pull/3141

### CODE REVIEW

**Comment by datarobot-devinfragit3** [comment]
pipelineController framework is deprecated, please migrate CICD for this repository to Harness

**Review by c-h-russell-walker — CHANGES_REQUESTED** [review]
Hi, apologies but I think this should be blocked until this ticket is taken care of:
https://datarobot.atlassian.net/browse/NB-5127

CC @roma-glushko 

We recently discovered notebooks were'nt working with the very latest `ipykernel` so need to pin them.

We could maybe include those changes in this PR as a way forward as well.

**Comment by c-h-russell-walker** [comment]
FYI @m-borkowski I've taken that ticket from @roma-glushko and it's my top priority now - do you mind if I "re-use" your branch and PR here?

**Comment by m-borkowski** [comment]
> FYI @m-borkowski I've taken that ticket from @roma-glushko and it's my top priority now - do you mind if I "re-use" your branch and PR here?

no problem :+1:

**Comment by m-borkowski** [comment]
@c-h-russell-walker hah yes, I did it, I thought the new issue has appeared this week

**Comment by c-h-russell-walker** [comment]
> @c-h-russell-walker hah yes, I did it, I thought the new issue has appeared this week

No just me being paranoid about releasing broken kernel images - lul.

**Review by zohar-mizrahi — APPROVED** [review]

**Comment by c-h-russell-walker** [comment]
Hi, apologies - posted [in other PR as well here](https://github.com/datarobot/datarobot-user-models/pull/925) but should I / do I need to wait for _this_ PR to be release before merging mine and releasing mine?

**Comment by m-borkowski** [comment]
hi @c-h-russell-walker from my perspective you can merge and release
I've not released it because, it was not high-priority, so can be released with other changes

**Pull request merged**
