### PR TITLE
[RAPTOR-3496] fix drum push

### PR DESCRIPTION
**Pull request by jlpolit**
# This repository is public. Do not put here any private DataRobot or customer's data: code, datasets, model artifacts, .etc.

## Summary

Drum push didn't have a bunch of stuff in its runtime (unsupervised, as well as a few monitoring fields). This handles those, and puts in a functional test to avoid breaking drum push by accident in the future.

Note- I moved the drum conftest up a level to use those fixtures....don't hesitate to tell me that was stupid

### CODE REVIEW

**Review by 4dahalibut — APPROVED** [review]

**Comment by 4dahalibut** [comment]
:love_you_gesture:

**Review by yakov-g — APPROVED** [review]

**Review by meltzg — APPROVED** [review]

**Comment by yakov-g** [comment]
jarvis please test functional_drop_in

**Comment by yakov-g** [comment]
jarvis please test functional_drop_in

**Comment by datarobot-jarvis** [comment]
:dollar: Total cost of executing tests in Jenkins: $**4.18** USD.

[What is this all about?](http://bit.ly/2BahK4V)

**Pull request merged**
