### PR TITLE
Switch R envs to flask because of OOM

### PR DESCRIPTION
**Pull request by yakov-g**
# This repository is public. Do not put here any private DataRobot or customer's data: code, datasets, model artifacts, .etc.

## Summary
R nginx started to fail with OOM
Switch to Flask

### CODE REVIEW

**Review by meltzg — APPROVED** [review]
why were we installing vim in the first place?

**Comment by yakov-g** [comment]
> why were we installing vim in the first place?

This is dev env, so I wanted to install vim

**Comment by yakov-g** [comment]
jarvis please test functional_drop_in

**Review by meltzg — APPROVED** [review]

**Comment by liororama** [comment]
What kind of failure we are talking about ? if we are using a single worker then NGINKS is not talking much more memory then the flask? And I prefer our default environments to use nginx and not flask server.

**Comment by yakov-g** [comment]
> What kind of failure we are talking about ? if we are using a single worker then NGINKS is not talking much more memory then the flask? And I prefer our default environments to use nginx and not flask server.

I don't know what has happened: 
the flow was.
1. Smth has changed in R repos, that required to rebuild R base image. Docker file hasn't been changed, I only recreated the image.
2. Tests started to fail.
3. Tests in R nginx env fail both on jenkins and locally
4. Tests in R flask env fail locally, but do not fail in jenkins.
5. I want to merge this to unblock development and investigate.

**Review by liororama — APPROVED** [review]
As long as this is for unblocking development I am ok with this.

**Comment by datarobot-jarvis** [comment]
:dollar: Total cost of executing tests in Jenkins: $**2.49** USD.

[What is this all about?](http://bit.ly/2BahK4V)

**Pull request merged**
