### PR TITLE
Release DRUM 1.1.4 and env update place holder

### PR DESCRIPTION
**Pull request by yakov-g**
# This repository is public. Do not put here any private DataRobot or customer's data: code, datasets, model artifacts, .etc.

## Summary
Placeholder for publishing DRUM and updating envs.

Once tests with `rcX` version pass, I publish drum 1.1.4 without rc suffix, and merge

### CODE REVIEW

**Comment by yakov-g** [comment]
jarvis test functional_drop_in

**Comment by yakov-g** [comment]
jarvis test functional_drop_in

**Comment by yakov-g** [comment]
jarvis test functional_drop_in

**Comment by datarobot-jarvis** [comment]
:dollar: Total cost of executing tests in Jenkins: $**6.54** USD.

[What is this all about?](http://bit.ly/2BahK4V)

**Pull request merged**
