### PR TITLE
[RAPTOR-8801] change test jobs run order (phases)

### PR DESCRIPTION
**Pull request by yakov-g**
# This repository is public. Do not put here any private DataRobot or customer's data: code, datasets, model artifacts, .etc.

## Summary
For unknown reason integration general tests fail if started together with java tests.
Run java tests first as this is quite a short job, and afterwards all the others.

There also some cleanups in the PR, but main change is - phases

### CODE REVIEW

**Comment by yakov-g** [comment]
jenkins run jenkins run test_integration_in_a_single_container

**Comment by yakov-g** [comment]
jenkins run run test_integration_in_a_single_container

**Comment by yakov-g** [comment]
jenkins run test_integration_in_a_single_container

**Comment by yakov-g** [comment]
jenkins run test_integration_general

**Review by rvorobii — APPROVED** [review]

**Comment by rvorobii** [comment]
@yakov-g please give the PR a more meaningful name

**Comment by yakov-g** [comment]
> @yakov-g please give the PR a more meaningful name

right, forgot

**Comment by yakov-g** [comment]
jenkins run test_integration_general

**Review by elatt — APPROVED** [review]

**Pull request merged**
