### PR TITLE
[RAPTOR-9234] copy only start_server.sh/fit.sh into the code dir

### PR DESCRIPTION
**Pull request by yakov-g**
# This repository is public. Do not put here any private DataRobot or customer's data: code, datasets, model artifacts, .etc.

## Summary
Make code dir inside environment cleaner by copying only start_server.sh/fit.sh into it.

### CODE REVIEW

**Comment by yakov-g** [comment]
jenkins run test_integration_python_keras  test_integration_python_xgboost test_integration_python_sklearn

**Comment by yakov-g** [comment]
jenkins run test_integration_python_keras  test_integration_python_xgboost test_integration_python_sklearn

**Comment by yakov-g** [comment]
jankins run test_integration_python_keras test_integration_python_onnx test_integration_python_pytorch test_integration_python_sklearn test_integration_python_xgboost test_integration_r_environment

**Comment by yakov-g** [comment]
jenkins run test_integration_python_keras test_integration_python_onnx test_integration_python_pytorch test_integration_python_sklearn test_integration_python_xgboost test_integration_r_environment

**Review by zohar-mizrahi — APPROVED** [review]

**Review by akshoop — APPROVED** [review]
LGTM from Core Modeling, CC @eric-s-s @scottp-ml for awareness

**Review by aslisabanci — COMMENTED** [review]
👌

**Pull request merged**
