### PR TITLE
[YOLO] update torch to 1.6.0

### PR DESCRIPTION
**Pull request by yakov-g**
# This repository is public. Do not put here any private DataRobot or customer's data: code, datasets, model artifacts, .etc.

## Summary
currently used `torch==1.2.0` is super old and is not supported by Py3.8.
Trying to update to 1.6.0

Speak up if you are against and suggest version to update to.

### CODE REVIEW

**Comment by yakov-g** [comment]
jarvis test cmrunner_integration

**Comment by yakov-g** [comment]
jarvis test cmrunner_integration

**Review by 4dahalibut — APPROVED** [review]

**Review by 4dahalibut — APPROVED** [review]

**Comment by yakov-g** [comment]
jarvis test functional_inference_model_templates

**Comment by yakov-g** [comment]
jarvis test cmrunner_integration

**Review by jmbannon — APPROVED** [review]

**Pull request merged**
