### PR TITLE
[WIP] remove line terminator

### PR DESCRIPTION
**Pull request by yakov-g**
# This repository is public. Do not put here any private DataRobot or customer's data: code, datasets, model artifacts, .etc.

### CODE REVIEW

**Comment by yakov-g** [comment]
jenkins run test_integration_python_sklearn

**Comment by yakov-g** [comment]
jenkins run test_integration_r_environment

**Comment by yakov-g** [comment]
jenkins run test_integration_r_environment test_integration_python_sklearn

**Comment by yakov-g** [comment]
jenkins run test_integration_r_environment test_integration_python_sklearn test_integration_python_keras

**Comment by elatt** [comment]
Closing due to inactivity.

**Pull request closed without merging**
