### PR TITLE
[RAPTOR-7458] don't install drum-base-predictor locally for test/build purposes

### PR DESCRIPTION
**Pull request by yakov-g**
com.datarobot.drum-base-predictor has been published to Maven repo.

# This repository is public. Do not put here any private DataRobot or customer's data: code, datasets, model artifacts, .etc.

### CODE REVIEW

**Review by alexey-kry — APPROVED** [review]

**Review by meltzg — APPROVED** [review]

**Review by alexey-kry — APPROVED** [review]

**Comment by yakov-g** [comment]
jarvis test cmrunner_integration

**Comment by yakov-g** [comment]
jarvis test cmrunner_integration

**Comment by yakov-g** [comment]
jarvis test cmrunner_integration

**Comment by yakov-g** [comment]
jarvis test cmrunner_integration

**Comment by yakov-g** [comment]
jarvis test cmrunner_integration

**Comment by yakov-g** [comment]
jarvis test cmrunner_integration

**Pull request merged**
