### PR TITLE
[RAPTOR-4106] add monitoring to R and Java predictors

### PR DESCRIPTION
**Pull request by yakov-g**
# This repository is public. Do not put here any private DataRobot or customer's data: code, datasets, model artifacts, .etc.

## Summary
Add monitoring to R and Java predictors.
Tested manually.

### CODE REVIEW

**Comment by yakov-g** [comment]
jarvis test functional_drop_in

**Comment by yakov-g** [comment]
jarvis test functional_drop_in

**Review by rvorobii — APPROVED** [review]
LGTM

**Review by meltzg — APPROVED** [review]

**Comment by yakov-g** [comment]
@rvorobii about monitoring....
I don't know....
We have `monitoring` and `push` which will work only with the APP. Should we hide these options? Or we could just mention that these are just DR related functionality....
That's like public API.  Client is open for everyone , but worth nothing without DR.

**Comment by datarobot-jarvis** [comment]
:dollar: Total cost of executing tests in Jenkins: $**8.77** USD.

[What is this all about?](http://bit.ly/2BahK4V)

**Pull request merged**
