### PR TITLE
[RAPTOR-3406] Make order of extensions and files deterministic in error messages

### PR DESCRIPTION
**Pull request by rvorobii**
# This repository is public. Do not put here any private DataRobot or customer's data: code, datasets, model artifacts, .etc.

## Summary
Make order of extensions and files deterministic in error messages + improve wording.

### CODE REVIEW

**Comment by yakov-g** [comment]
jarvis test black

**Comment by yakov-g** [comment]
jarvis please test cmrunner_integration

**Comment by yakov-g** [comment]
jarvis please test functional_drop_in

**Comment by datarobot-jarvis** [comment]
:dollar: Total cost of executing tests in Jenkins: $**1.26** USD.

[What is this all about?](http://bit.ly/2BahK4V)

**Pull request merged**
