### PR TITLE
[RAPTOR-10171] add a separate job for integration tests

### PR DESCRIPTION
**Pull request by yakov-g**
# This repository is public. Do not put here any private DataRobot or customer's data: code, datasets, model artifacts, .etc.

## Summary
* add a separate job for integration tests
* update drum-builder image; already pushed

### CODE REVIEW

**Comment by yakov-g** [comment]
jenkins run test_integration

**Comment by yakov-g** [comment]
jenkins run build_drum

**Comment by yakov-g** [comment]
jenkins run test_integration

**Comment by yakov-g** [comment]
jenkins run test_integration

**Comment by yakov-g** [comment]
jenkins run test_integration

**Comment by yakov-g** [comment]
jenkins run test_integration

**Comment by yakov-g** [comment]
jenkins run test_integration

**Comment by yakov-g** [comment]
jenkins run test_integration

**Comment by yakov-g** [comment]
jenkins run test_integration

**Comment by yakov-g** [comment]
jenkins run test_integration

**Comment by yakov-g** [comment]
jenkins run test_integration

**Comment by yakov-g** [comment]
jenkins run test_integration

**Comment by yakov-g** [comment]
jenkins run test_integration

**Comment by yakov-g** [comment]
jenkins run drum_build

**Comment by yakov-g** [comment]
jenkins run build_drum

**Comment by yakov-g** [comment]
jenkins run test_integration

**Comment by yakov-g** [comment]
jenkins run test_integration

**Comment by yakov-g** [comment]
jenkins run drum_build

**Comment by yakov-g** [comment]
jenkins run build_drum

**Review by eric-s-s — APPROVED** [review]
nice!

**Comment by yakov-g** [comment]
jenkins run test_functional_r_environment

**Comment by yakov-g** [comment]
jenkins run continuous-integration/jenkins/pr-merge

**Review by rvorobii — APPROVED** [review]

**Pull request merged**
