### PR TITLE
Retroactively merge  back 1.6.7 

### PR DESCRIPTION
**Pull request by klichukb**
# This repository is public. Do not put here any private DataRobot or customer's data: code, datasets, model artifacts, .etc.

### CODE REVIEW

**Review by meltzg — APPROVED** [review]

**Comment by klichukb** [comment]
jarvis please test this

**Review by alexey-kry — APPROVED** [review]

**Review by rvorobii — APPROVED** [review]

**Comment by klichukb** [comment]
jarvis please test functional_training_model_templates

**Comment by klichukb** [comment]
jarvis please test functional_training_model_templates

**Comment by klichukb** [comment]
jarvis please test functional_training_model_templates

**Pull request merged**
