### PR TITLE
[RAPTOR-10071] Increase verbosity of the drop-in environments test

### PR DESCRIPTION
**Pull request by zohar-mizrahi**
# This repository is public. Do not put here any private DataRobot or customer's data: code, datasets, model artifacts, .etc.

## Summary
Increase the verbosity of the given test to easily track test progress.

### CODE REVIEW

**Comment by zohar-mizrahi** [comment]
jarvis please test test_integration_r_environment

**Review by yakov-g — APPROVED** [review]

**Comment by yakov-g** [comment]
jenkins run test_inference_model_templates

**Review by klichukb — APPROVED** [review]

**Comment by yakov-g** [comment]
jenkins run pipelineController:all-expected-tasks

**Comment by yakov-g** [comment]
jenkins run test_integration_r_environment

**Pull request merged**
