### PR TITLE
[RAPTOR-8364] Check env var before printing env dump

### PR DESCRIPTION
**Pull request by rvorobii**
# This repository is public. Do not put here any private DataRobot or customer's data: code, datasets, model artifacts, .etc.

## Summary
Only print environment variables if `ENABLE_CUSTOM_MODEL_RUNTIME_ENV_DUMP` is set.

### CODE REVIEW

**Comment by rvorobii** [comment]
jarvis check this

**Review by jlandersen — APPROVED** [review]
👍 (sort of a miss click on review - i'll let @yakov-g chip in as well since it's DRUM, but looks benign and good)

**Review by akshoop — APPROVED** [review]

**Comment by yakov-g** [comment]
jenkins run test_integration_r_environment

**Comment by rvorobii** [comment]
jarvis test test_integration_r_environment

**Comment by rvorobii** [comment]
jenkins run continuous-integration/jenkins/pr-merge

**Pull request merged**
