### PR TITLE
[RAPTOR-10296] bump pillow<=10.2.0, update envs, release v1.10.19

### PR DESCRIPTION
**Pull request by yakov-g**
# This repository is public. Do not put here any private DataRobot or customer's data: code, datasets, model artifacts, .etc.

## Summary
Bump pillow<=10.2.0 to fix CVE, update envs, release v1.10.19

### CODE REVIEW

**Review by zohar-mizrahi — APPROVED** [review]

**Review by c-h-russell-walker — APPROVED** [review]
Looks good, thanks so much for making this update.

**Review by akshoop — APPROVED** [review]
LGTM from Core Modeling

**Comment by akshoop** [comment]
CC @mxpoliakov for awareness on behalf of GenAI

**Review by amatanasov — APPROVED** [review]

**Comment by yakov-g** [comment]
jenkins run test_functional_general

**Pull request merged**
