### PR TITLE
[RAPTOR-9422-9423] bump werkzeug flask markupsafe deps, release 1.10.4

### PR DESCRIPTION
**Pull request by yakov-g**
# This repository is public. Do not put here any private DataRobot or customer's data: code, datasets, model artifacts, .etc.

## Summary
* bump werkzeug flask markupsafe deps
* switch some test scripts from quantum to a regular py venv
* prepare for 1.10.4 release

### CODE REVIEW

**Comment by yakov-g** [comment]
jenkins run test_integration_r_environment

**Comment by yakov-g** [comment]
jenkins run test_integration_general

**Comment by yakov-g** [comment]
jenkins run test_integration_general

**Comment by yakov-g** [comment]
jenkins run test_integration_general

**Comment by yakov-g** [comment]
jenkins run test_integration_general

**Comment by yakov-g** [comment]
jenkins run test_integration_general

**Comment by yakov-g** [comment]
jenkins run test_integration_general

**Comment by yakov-g** [comment]
jenkins run test_integration_general

**Comment by yakov-g** [comment]
jenkins run test_integration_general

**Comment by yakov-g** [comment]
jenkins run test_integration_general

**Comment by yakov-g** [comment]
@c-h-russell-walker just FYI. Updating packages you are waiting for. I ran `trivy`, it shows issues are fixed.

**Comment by yakov-g** [comment]
jenkins run test_integration_general

**Review by akshoop — APPROVED** [review]
LGTM from Core Modeling

**Comment by yakov-g** [comment]
jenkins run test_integration_r_environment

**Comment by yakov-g** [comment]
jenkins run test_integration_python_keras

**Review by jknthn — APPROVED** [review]
LGTM, good to keep things updated!

**Comment by yakov-g** [comment]
jenkins run ontinuous-integration/jenkins/pr-merge

**Pull request merged**
