### PR TITLE
[RAPTOR-9199] update pyarrow to <=10.0.1

### PR DESCRIPTION
**Pull request by yakov-g**
# This repository is public. Do not put here any private DataRobot or customer's data: code, datasets, model artifacts, .etc.

## Summary
I had a meeting with a customer who uses Mac M1 - ARM based laptops. So they need public environment image built for ARM.
We need to support AMD/ARM arch for our base images.
I succeeded to build such an image, https://hub.docker.com/layers/datarobot/dropin-env-base/debian11-py3.9-jre11.0.16-drum1.10.1.rc1-mlops8.2.7-multiplatform-test/images/sha256-b072ee076a076c0f9468850ba0ae86ccd8c4bd67e764a950bc35380c7b376750?context=repo

Though I had a problem with previously constrained pyarrow <= 3.0.0 - was not able to build ARM image with pyarrow <=3.0.
So i decided to bump it to <=10.0.1 (not 11 as it conflicts with tensorflow). 
I bumped in both DRUM and envs.  Constraint in DRUM is what important to build the base image.
If tighter constrains are needed they can be done in env, while DRUM will be more flexible.

Once I confirm with the customer that it works, I'll update all our base images

### CODE REVIEW

**Comment by yakov-g** [comment]
jenkins run test_integration_general

**Comment by yakov-g** [comment]
jenkins run continuous-integration/jenkins/pr-merge

**Review by akshoop — APPROVED** [review]
LGTM from Core Modeling, CC @eric-s-s @scottp-ml for awareness

**Review by scottp-ml — APPROVED** [review]
LGTM

**Review by jlandersen — APPROVED** [review]
👍

**Pull request merged**
