### PR TITLE
[RAPTOR-10131] reorder test by putting heavier envs first

### PR DESCRIPTION
**Pull request by yakov-g**
# This repository is public. Do not put here any private DataRobot or customer's data: code, datasets, model artifacts, .etc.

## Summary
This test is unstable in DataRobot Daily Suite, reorder to put heavier envs in the beginning to figure out whether it may be resources related issue.

### CODE REVIEW

**Review by zohar-mizrahi — APPROVED** [review]

**Comment by yakov-g** [comment]
jenkins run test_functional_general

**Review by rvorobii — APPROVED** [review]

**Comment by yakov-g** [comment]
jenkins run test_functional_general

**Comment by yakov-g** [comment]
jenkins run test_functional_general

**Comment by yakov-g** [comment]
jenkins run test_functional_general

**Pull request merged**
