### PR TITLE
Deps up: pandas==1.1.0, numpy==1.19.0

### PR DESCRIPTION
**Pull request by yakov-g**
# This repository is public. Do not put here any private DataRobot or customer's data: code, datasets, model artifacts, .etc.

## Summary
Bumping deps version in a couple of places i missed.

### CODE REVIEW

**Comment by klichukb** [comment]
I believe as we go further this would be considered a really breaking change. Not sure about now :)

**Comment by klichukb** [comment]
Might requalify it to "major", not "breaking" since it would affect only new models.

**Comment by yakov-g** [comment]
To tell the truth, I look at these envs only as envs for our model templates - examples.
If anyone needs his specific requirements - provide them with your model.

A couple of hours ago I merged a PR where I bumped pandas in several places, because I wanted to upgrade rpy2 and unify dependencies.

Having different deps across envs also doesn't look clear clear to me.
So this PR is only bump in two places as I bumped in 20 other places before.

**Comment by meltzg** [comment]
@yakov-g these envs are not templates/examples. they're part of the product. these are the exact environments that are installed as public envs

**Comment by klichukb** [comment]
Kinda of agree that its only template, but at the same time, I meant that they are then ending up in dR cloud as default envs to go. 

No problem at this point, would be interesting to see if anything break

**Comment by yakov-g** [comment]
I meant these are envs for our model templates at first place.
I agree with you both, they are part of the product, but in this case we shouldn't touch them at all. And all our newly introduced examples (model templates) shouldn't change these envs. Thus we need to create separate envs where our examples run.

Maybe we even should go further:
have 3 public envs py/java/r and move requirements into models. This will also remind CFDSs and customers to provide proper requirements with the model and not to rely on env. (I'm not sure if dependency management is available for self service)

**Comment by yakov-g** [comment]
@meltzg @klichukb 
And could you approve?

**Review by meltzg — APPROVED** [review]

**Review by rvorobii — APPROVED** [review]

**Comment by datarobot-jarvis** [comment]
:dollar: Total cost of executing tests in Jenkins: $**2.47** USD.

[What is this all about?](http://bit.ly/2BahK4V)

**Pull request merged**
