### PR TITLE
[MMM-13720] Remove hard coded target name for text generation target type

### PR DESCRIPTION
**Pull request by amarmudrankit**
Initially, DRUM did not need the target name for text generation target type and we use the target name “COMPLETION” for it.  It seems like it could create multiple issues, so removing this hard coding and using the configured target name like any other typical target type (eg. Regression)

# This repository is public. Do not put here any private DataRobot or customer's data: code, datasets, model artifacts, .etc.

### CODE REVIEW

**Comment by amarmudrankit** [comment]
jenkins run test_integration_python_sklearn

**Comment by amarmudrankit** [comment]
jenkins run test_integration_general

**Comment by amarmudrankit** [comment]
jenkins test test_training_model_templates

**Comment by amarmudrankit** [comment]
jenkins test test_integration_general

**Review by yakov-g — APPROVED** [review]
Let't rename REGRESSION_PRED_COLUMN->PRED_COLUMN
and write an extensive comment that is is used for regression and text generation.

**Comment by yakov-g** [comment]
jenkins run test_drop_in_envs

**Review by akshoop — APPROVED** [review]

**Pull request merged**
