### PR TITLE
[NB-5720][NB-5238] Add dependencies to kernels

### PR DESCRIPTION
**Pull request by tpadr**
## Summary
Updated notebooks kernels:
* Added `gh` (GitHub CLI)
* Added  `boto3` and `sagemaker`  to python kernels (except deprecated python3.8)
* Update `datarobot==3.4.0` CC @asuslov

### CODE REVIEW

**Comment by tpadr** [comment]
jenkins run test_functional_r_environment

**Comment by tpadr** [comment]
jenkins run test_functional_python_keras

**Review by c-h-russell-walker — APPROVED** [review]
Looks great.

**Review by rvorobii — APPROVED** [review]

**Review by asuslov — APPROVED** [review]
Thanks for bumping pysdk version for us!

**Comment by tpadr** [comment]
jenkins run unitintegration-test_unit

**Comment by tpadr** [comment]
jenkins run test_functional_r_environment

**Comment by tpadr** [comment]
jenkins run unitintegration-test_unit

**Comment by rvorobii** [comment]
jenkins run unitintegration

**Pull request merged**
