### PR TITLE
[RAPTOR-2994] Fix functional tests after API update

### PR DESCRIPTION
**Pull request by rvorobii**
# This repository is public. Do not put here any private DataRobot or customer's data: code, datasets, model artifacts, .etc.

### CODE REVIEW

**Comment by 4dahalibut** [comment]
@yakov-g what does your comment mean? what tests were deleted?

**Comment by datarobot-jarvis** [comment]
:dollar: Total cost of executing tests in Jenkins: $**1.5** USD.

[What is this all about?](http://bit.ly/2BahK4V)

**Comment by datarobot-jarvis** [comment]
:dollar: Total cost of executing tests in Jenkins: $**1.93** USD.

[What is this all about?](http://bit.ly/2BahK4V)

**Comment by rvorobii** [comment]
thank you @4dahalibut!

**Pull request merged**
