### PR TITLE
[RAPTOR-11574] update DRUM version in environments

### PR DESCRIPTION
**Pull request by yakov-g**
# This repository is public. Do not put here any private DataRobot or customer's data: code, datasets, model artifacts, .etc.

## Summary
Bump DRUM in the environments to make them have the latest for the release

### CODE REVIEW

**Comment by baekdahl** [comment]
@yakov-g Can we please release a new DRUM first? Would like to get my changes in #1139 into latest environments

**Review by YuriyGuts — APPROVED** [review]
LGTM GenAI

**Comment by yakov-g** [comment]
@baekdahl is it ok to bump drum in the 3.11 GenAi env?

**Review by baekdahl — APPROVED** [review]
@yakov-g Yes, that's great. Sorry forgot to approve this yesterday.

**Review by rvorobii — APPROVED** [review]

**Review by akshoop — APPROVED** [review]

**Pull request merged**
