### PR TITLE
Uncomment test_drum_push

### PR DESCRIPTION
**Pull request by yakov-g**
# This repository is public. Do not put here any private DataRobot or customer's data: code, datasets, model artifacts, .etc.

## Summary
Commented out this test_drum_push because installing DRUM fails in quantum. Before it worked.
Need to check with quantum team if it doesn't pass.

### CODE REVIEW

**Review by 4dahalibut — APPROVED** [review]

**Comment by yakov-g** [comment]
jarvis test functional_drop_in

**Comment by yakov-g** [comment]
jarvis test functional_drop_in

**Comment by yakov-g** [comment]
jarvis test functional_drop_in

**Comment by yakov-g** [comment]
jarvis test functional_drop_in

**Comment by yakov-g** [comment]
jarvis test functional_drop_in

**Review by rvorobii — APPROVED** [review]

**Comment by yakov-g** [comment]
jarvis test cmrunner_integration

**Comment by datarobot-jarvis** [comment]
:dollar: Total cost of executing tests in Jenkins: $**4.76** USD.

[What is this all about?](http://bit.ly/2BahK4V)

**Pull request merged**
