### PR TITLE
[RAPTOR-8728] bump mlpiper, log4j, release 1.9.13

### PR DESCRIPTION
**Pull request by yakov-g**
# This repository is public. Do not put here any private DataRobot or customer's data: code, datasets, model artifacts, .etc.

## Summary
- Bump mlpiper to 2.6.0 version with fixed log4j
- bump log4j to 2.19.0
- add example on log4j custom logger init
- update envs

### CODE REVIEW

**Comment by yakov-g** [comment]
jenkins run test_integration_general

**Comment by yakov-g** [comment]
jenkins run test_integration_general

**Comment by yakov-g** [comment]
jenkins run test_integration_general

**Comment by yakov-g** [comment]
kins run test_integration_general

**Comment by yakov-g** [comment]
jenkins run test_integration_general

**Comment by yakov-g** [comment]
jenkins run test_integration_general

**Review by akshoop — APPROVED** [review]
LGTM from Core Modeling

**Review by rvorobii — APPROVED** [review]

**Pull request merged**
