### PR TITLE
[Yolo] bug fix in score.jl

### PR DESCRIPTION
**Pull request by timsetsfire**
a small bug was present in the score.jl language predictor.  If a MLJ artificat was provided with custom.jl file which defined load_hook and no score hook, then necessary libraries to complete scoring would not be loaded. 

# This repository is public. Do not put here any private DataRobot or customer's data: code, datasets, model artifacts, .etc.

### CODE REVIEW

**Review by yakov-g — APPROVED** [review]

**Comment by timsetsfire** [comment]
jenkins cmrunner_integration

**Comment by timsetsfire** [comment]
jarvis test cmrunner_integration

**Comment by 4dahalibut** [comment]
this could have test coverage

**Comment by 4dahalibut** [comment]
did you manually test?

**Comment by timsetsfire** [comment]
Yes.  sorry i didn't post more detail.  The main issue was that if a custom `load_model` was defined then a custom `score` must because the logic in the score.jl resulted in skipping the loading libraries necessary to use the default scoring method if a custom `load_model` was used.  I only caught this when i went with a slightly more complex julia model that required a custom load_model function but should not have required a custom score function.  

Test coverage might be a good idea -> maybe a test for custom.py with single hooks defined.  Not sure.

**Review by rvorobii — APPROVED** [review]

**Pull request merged**
