### PR TITLE
Yakov/test refactoring

### PR DESCRIPTION
**Pull request by yakov-g**
# This repository is public. Do not put here any private DataRobot or customer's data: code, datasets, model artifacts, .etc.

### CODE REVIEW

**Comment by yakov-g** [comment]
jarvis test black_check

**Comment by yakov-g** [comment]
jarvis test black_check

**Comment by yakov-g** [comment]
jarvis test black_check

**Comment by yakov-g** [comment]
jarvis test black_check

**Comment by yakov-g** [comment]
jarvis test integration

**Comment by yakov-g** [comment]
jarvis test integration

**Comment by yakov-g** [comment]
jarvis test integration

**Comment by yakov-g** [comment]
jarvis test integration

**Comment by yakov-g** [comment]
jarvis test black_check

**Comment by yakov-g** [comment]
jarvis test test_integration_python_sklearn

**Comment by yakov-g** [comment]
jarvis test build_drum

**Comment by yakov-g** [comment]
jarvis test test_integration_python_sklearn

**Comment by andrey-hura** [comment]
jenkins run build_drum test_inference_model_templates

**Comment by andrey-hura** [comment]
jenkins run build_drum test_inference_model_templates

**Comment by andrey-hura** [comment]
jenkins run build_drum test_inference_model_templates

**Comment by yakov-g** [comment]
jenkins run build_drum test_integration_python_sklearn

**Comment by yakov-g** [comment]
jarvis run test_integration_r_environment

**Comment by yakov-g** [comment]
jarvis run continuous-integration/jenkins/pr-merge

**Comment by yakov-g** [comment]
jenkins run test_integration_python_sklearn

**Comment by andrey-hura** [comment]
jenkins run pipelineController:all-expected-tasks

**Comment by yakov-g** [comment]
jarvis run test_integration_in_a_single_container

**Pull request closed without merging**
