### PR TITLE
[RAPTOR-3569] change start_server.sh/fit.sh to take target_type from …

### PR DESCRIPTION
**Pull request by yakov-g**
change start_server.sh/fit.sh to take target_type from LRS env var

# This repository is public. Do not put here any private DataRobot or customer's data: code, datasets, model artifacts, .etc.

### CODE REVIEW

**Comment by rvorobii** [comment]
we need to have these environments updated to on prod only when https://github.com/datarobot/DataRobot/pull/71133 os deployed there

**Review by rvorobii — APPROVED** [review]
we need to have these environments updated to on prod only when datarobot/DataRobot#71133 os deployed there

**Comment by yakov-g** [comment]
> we need to have these environments updated to on prod only when [datarobot/DataRobot#71133](https://github.com/datarobot/DataRobot/pull/71133) os deployed there

Good point. When does this happen?

**Comment by rvorobii** [comment]
> > we need to have these environments updated to on prod only when [datarobot/DataRobot#71133](https://github.com/datarobot/DataRobot/pull/71133) os deployed there
> 
> Good point. When does this happen?

we have cloud deploys weekly, used to be on Wed
we can ask supersully from time to time in Slack `@supersully pr RAPTOR-3569`

**Review by meltzg — CHANGES_REQUESTED** [review]
env version ids should be updated.  Also, we shouldn't merge this until the change to DR makes its way to prod

**Review by meltzg — APPROVED** [review]

**Comment by datarobot-jarvis** [comment]
:dollar: Total cost of executing tests in Jenkins: $**4.07** USD.

[What is this all about?](http://bit.ly/2BahK4V)

**Pull request merged**
