### PR TITLE
VIZAI-1568 add image object detection custom inference model template

### PR DESCRIPTION
**Pull request by Dicksonchin93**
# This repository is public. Do not put here any private DataRobot or customer's data: code, datasets, model artifacts, .etc.

## Summary
Add image object detection custom inference model in unstructured mode, demo video for internal reference https://drive.google.com/file/d/11iRcrhvis6HsxpZrmJjOJ5_K_eqO8i05/view?usp=sharing

### CODE REVIEW

**Comment by yakov-g** [comment]
Thanks for this great example, especially it is for unstructured mode. We definitely want to keep it - the question is - where. 
Looks like it is time to stop adding examples into this repo. Models in this repo are intended to be not complex, and used for testing and example purposes.

We already have another VIZAI example https://github.com/datarobot/datarobot-user-models/tree/master/model_templates/inference/python3_keras_vizai_joblib which is commented out from the tests because of some space issues, so it's just sitting here without (probably) any attention.

So I'd suggest putting these two examples into some popular CFDSs' related repo, mark it as CustomModel/DRUM example and put a link on it into documentation.

The only downside could be that this repo is public, so those examples won't be accessible from outside, unless there is some CFDS related public repo.

What do you think? @Dicksonchin93  @meltzg @klichukb @4dahalibut @scottp-ml

**Comment by meltzg** [comment]
@yakov-g the vizai model was disabled during tests because it pulls some artifact from the public internet, which breaks the test since that feature is not enabled. If this does not have that issue, i'd say we replace the existing example

**Comment by scottp-ml** [comment]
We can also consider creating a repo that is publicly accessible just for examples and templates.

**Comment by yakov-g** [comment]
There is a repo: https://github.com/datarobot-community/mlops-examples/tree/master/MLOps_DRUM/other_models

**Comment by Dicksonchin93** [comment]
Is there a consensus here? I'm fine placing the code in https://github.com/datarobot-community/mlops-examples/tree/master/MLOps_DRUM/other_models too

**Review by meltzg — CHANGES_REQUESTED** [review]
I'd say just keep it in the MLOps community repo

**Comment by yakov-g** [comment]
Probably it should go here: https://github.com/datarobot-community/mlops-examples/tree/master/MLOps_DRUM

@timsetsfire  please comment

**Comment by timsetsfire** [comment]
> Probably it should go here: https://github.com/datarobot-community/mlops-examples/tree/master/MLOps_DRUM
> 
> @timsetsfire please comment

indeed.  that spot makes the most sense for the time being.

**Comment by yakov-g** [comment]
> > Probably it should go here: https://github.com/datarobot-community/mlops-examples/tree/master/MLOps_DRUM
> > @timsetsfire please comment
> 
> indeed. that spot makes the most sense for the time being.

@Dicksonchin93 once you move your code to the community repo, please add a link here: https://github.com/datarobot/datarobot-user-models/blob/master/README.md#sample-models
or let @scottp-ml know, as he's working on docs.
Thanks

**Comment by Dicksonchin93** [comment]
@yakov-g who can I talk to to give me permissions to push changes and make a PR in the mlops-examples repo?

**Comment by yakov-g** [comment]
> @yakov-g who can I talk to to give me permissions to push changes and make a PR in the mlops-examples repo?

I asked @timsetsfire to answer this question

**Comment by yakov-g** [comment]
> > @yakov-g who can I talk to to give me permissions to push changes and make a PR in the mlops-examples repo?
> 
> I asked @timsetsfire to answer this question

From Tim:
You can start with @Thodoris Petropoulos
but i've asked in the past for myself and they wouldn't give me persmission that repo
they made me go to some WIP repo and i just told them when i was ready and they moved everything over from the WIP repo to the regular one
i quit contributing to community because it was such a process was annoying

**Comment by Dicksonchin93** [comment]
WIP PR in https://github.com/datarobot-community/mlops-examples/pull/2, got approval from Thodoris through slack, he can't see this PR and the discussions we had here

**Pull request closed without merging**
