### PR TITLE
[RAPTOR-8060] bump java jackson packages to 2.13.3 - drop 2

### PR DESCRIPTION
**Pull request by yakov-g**
# This repository is public. Do not put here any private DataRobot or customer's data: code, datasets, model artifacts, .etc.

## Summary
- bump a missed dependency
- fix script to take into account all the runs of pytest

### CODE REVIEW

**Comment by yakov-g** [comment]
jarvis test cmrunner_integration

**Review by akshoop — APPROVED** [review]

**Review by rvorobii — APPROVED** [review]

**Comment by yakov-g** [comment]
jarvis test functional_drop_in functional_inference_model_templates

**Comment by yakov-g** [comment]
jenkins test cmrunner_integration functional_inference_model_templates

**Comment by yakov-g** [comment]
jarvis test functional_inference_model_templates

**Pull request merged**
