### PR TITLE
[MMM-14493] bump dmm library

### PR DESCRIPTION
**Pull request by m-borkowski**
# This repository is public. Do not put here any private DataRobot or customer's data: code, datasets, model artifacts, .etc.

### CODE REVIEW

**Comment by m-borkowski** [comment]
jenkins run failed

**Comment by m-borkowski** [comment]
jarvis rerun failed

**Comment by m-borkowski** [comment]
jarvis test this

**Comment by m-borkowski** [comment]
jenkins run pipelineController:all-expected-tasks

**Comment by m-borkowski** [comment]
jenkins run pipelineController:all-expected-tasks

**Comment by dmytrokarpovych** [comment]
@m-borkowski 
Every time we make changes at this repo we should bump `environmentVersionId`

It could be do by `python ./tools/env_version_update.py -d public_dropin_notebook_environments` command

I pushed such changes for this PR

**Comment by m-borkowski** [comment]
> @m-borkowski Every time we make changes at this repo we should bump `environmentVersionId`
> 
> It could be do by `python ./tools/env_version_update.py -d public_dropin_notebook_environments` command
> 
> I pushed such changes for this PR

Thank you!

**Review by rvorobii — APPROVED** [review]

**Comment by rvorobii** [comment]
jenkins run test_integration_java_environment

**Comment by m-borkowski** [comment]
jenkins run pipelineController:all-expected-tasks

**Review by DrewParallel — APPROVED** [review]

**Pull request merged**
