### PR TITLE
[RAPTOR-3084] Remove todo and add comment

### PR DESCRIPTION
**Pull request by rvorobii**
# This repository is public. Do not put here any private DataRobot or customer's data: code, datasets, model artifacts, .etc.

### CODE REVIEW

**Comment by rvorobii** [comment]
this is weird why the tests are failing?
@yakov-g do you have an idea?

**Comment by yakov-g** [comment]
jarvis test cmrunner_integration

**Comment by datarobot-jarvis** [comment]
:dollar: Total cost of executing tests in Jenkins: $**1.0** USD.

[What is this all about?](http://bit.ly/2BahK4V)

**Comment by rvorobii** [comment]
thanks @yakov-g !

**Pull request merged**
