### PR TITLE
[NB-5277] [NB-5278] [NB-5279] Recent NBX updates to kernels

### PR DESCRIPTION
**Pull request by c-h-russell-walker**
# This repository is public. Do not put here any private DataRobot or customer's data: code, datasets, model artifacts, .etc.

## UPDATES

- The latest https://pypi.org/project/datarobot-drum/  is in the notebooks repo (it took care of a Pillow CVE) but not in the public drop-in Envs in this repo. yet
- Pinning the version `jupyter-client==7.4.9` helped us (NBX) lower the kernel startup time (also I moved where `ipykernel` is pinned just to match where it shows up in the NBX notebooks repo. for consistency)
- Updated the `setup-ssh.sh` script - this fixes an issue that arose with Env Vars that had either spaces in them or special characters like `'!'`

### CODE REVIEW

**Comment by datarobot-devinfragit3** [comment]
pipelineController framework is deprecated, please migrate CICD for this repository to Harness

**Comment by roma-glushko** [comment]
@c-h-russell-walker  I would not include https://github.com/datarobot/notebooks/pull/3134 into this one. Will port that change after the SaaS deployment is done

**Review by roma-glushko — APPROVED** [review]
Perfect 👍

**Comment by c-h-russell-walker** [comment]
> @c-h-russell-walker I would not include [datarobot/notebooks#3134](https://github.com/datarobot/notebooks/pull/3134) into this one. Will port that change after the SaaS deployment is done

Ah, I actually forgot about that one! 🙈 
Should we make a ticket for that in public-drop-ins as well?

TBH I think I'd like to bring up this maintenance in our next retro to see if we can define a good process for it 😎

**Comment by c-h-russell-walker** [comment]
jarvis please test test_functional_general

**Comment by datarobot-devinfragit3** [comment]
pipelineController framework is deprecated, please migrate CICD for this repository to Harness

**Review by zohar-mizrahi — APPROVED** [review]
LGTM

**Comment by datarobot-devinfragit3** [comment]
pipelineController framework is deprecated, please migrate CICD for this repository to Harness

**Comment by c-h-russell-walker** [comment]
@zohar-mizrahi and @m-borkowski I'd like to merge this PR and then build images and release them - as outlined in this confluence doc:
https://datarobot.atlassian.net/wiki/spaces/NBX/pages/5498011654/How+to+update+NBX+drop-ins+in+DataRobot#4.-Build-%26-Install-Drop-in-environments-on-staging%2Fproduction%3A

However there was a recently merged Notebooks drop-ins PR - seen here:
https://github.com/datarobot/datarobot-user-models/pull/924

Should I wait until that one ^^ is released?

**Pull request merged**
